import {
	PHOTO_UPLOAD_ACCEPT_ATTRIBUTE,
	PHOTO_UPLOAD_MAX_INPUT_SIZE_MB,
} from "@/shared/configs/photo-upload.config";

export const UPLOAD_DROP_ZONE_ACCEPT = PHOTO_UPLOAD_ACCEPT_ATTRIBUTE;
export const UPLOAD_FILE_SIZE_LIMIT_MB = PHOTO_UPLOAD_MAX_INPUT_SIZE_MB;
