export const PHOTO_UPLOAD_COMPRESSION_START_QUALITY = 90;
export const PHOTO_UPLOAD_COMPRESSION_MIN_QUALITY = 10;
export const PHOTO_UPLOAD_COMPRESSION_QUALITY_STEP = 10;
export const PHOTO_UPLOAD_MAX_DIMENSION_PX = 2000;
