name: publish-docker-image-exif

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: labmgm/rensa-exif:$DOCKER_IMAGE_TAG
