name: publish-docker-image-notification

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: ../../apps/notifications/Dockerfile
          push: true
          tags: labmgm/rensa-notification:$DOCKER_IMAGE_TAG
