name: ci-staging

on:
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_TAG: staging

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push ai image
        uses: ./publish-docker-image-ai.yml

      - name: Build and push web image
        uses: ./publish-docker-image-web.yml

      - name: Build and push exif image
        uses: ./publish-docker-image-exif.yml
